# Assignment 2

## Prediction of the Benzene content in the air using the Air Quality dataset

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
import zipfile
import pandas as pd
import urllib.request
import io

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\Sakinah\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\Sakinah\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\Sakinah\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\Sakinah\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Sakinah\AppData\Local\Temp\ipykernel_22788\3944362637.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\pandas\__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\pandas\core\api.py", line 1, in <module>
    from pandas._libs import (
  File "C:\Users\Sakinah\anaconda3\Lib\site-packages\pandas\_libs\__init__.py", line 17, in <module>
    import pandas._libs.pandas_datetime  # noqa: F401 # isort: skip # type: ignore[reportUnusedImport]

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

ImportError: numpy.core.multiarray failed to import

#### Dataset Link

In [6]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00360/AirQualityUCI.zip'

#### Loading the file using ZipFile Library

In [8]:
response = urllib.request.urlopen(url)
zip_file = zipfile.ZipFile(io.BytesIO(response.read()))

In [9]:
with zip_file.open('AirQualityUCI.csv') as file:
    data = pd.read_csv(file, sep=';', decimal=',', parse_dates={'Datetime': ['Date', 'Time']}, na_values=-200)

In [10]:
data.head()

,Datetime,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,10/03/2004 18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578,NaN,NaN
1,10/03/2004 19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255,NaN,NaN
2,10/03/2004 20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502,NaN,NaN
3,10/03/2004 21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867,NaN,NaN
4,10/03/2004 22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888,NaN,NaN

#### Assignning a new variable

In [12]:
data_pd = data.copy()

In [13]:
data_pd

,Datetime,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,10/03/2004 18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578,NaN,NaN
1,10/03/2004 19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255,NaN,NaN
2,10/03/2004 20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502,NaN,NaN
3,10/03/2004 21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867,NaN,NaN
4,10/03/2004 22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9466,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9467,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9468,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9469,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9470,nan nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### As there are many null values which are visible, we try to make a count of the null values

In [15]:
data_pd.isnull().sum()

Datetime            0
CO(GT)           1797
PT08.S1(CO)       480
NMHC(GT)         8557
C6H6(GT)          480
PT08.S2(NMHC)     480
NOx(GT)          1753
PT08.S3(NOx)      480
NO2(GT)          1756
PT08.S4(NO2)      480
PT08.S5(O3)       480
T                 480
RH                480
AH                480
Unnamed: 15      9471
Unnamed: 16      9471
dtype: int64

#### Dropping the null values along the columns using "axis=1" where all the points are null using "how='all' "

In [17]:
data_pd = data_pd.dropna(axis=1,how='all')

##### The columns 'Unnamed: 15' and 'Unnamed: 16' will be removed

In [19]:
data_pd.head()

,Datetime,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,10/03/2004 18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,10/03/2004 19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,10/03/2004 20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,10/03/2004 21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,10/03/2004 22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888

#### Dropping the rows having null values

In [21]:
data_pd = data_pd.dropna()

In [22]:
data_pd

,Datetime,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,10/03/2004 18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,10/03/2004 19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,10/03/2004 20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,10/03/2004 21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,10/03/2004 22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1226,30/04/2004 20.00.00,4.4,1449.0,501.0,19.5,1282.0,254.0,625.0,133.0,2100.0,1569.0,19.1,61.1,1.3345
1227,30/04/2004 21.00.00,3.1,1363.0,234.0,15.1,1152.0,189.0,684.0,110.0,1951.0,1495.0,18.2,65.4,1.3529
1228,30/04/2004 22.00.00,3.0,1371.0,212.0,14.6,1136.0,174.0,689.0,102.0,1927.0,1471.0,18.1,66.1,1.3579
1229,30/04/2004 23.00.00,3.1,1406.0,275.0,13.7,1107.0,167.0,718.0,108.0,1872.0,1384.0,17.7,66.9,1.3422
1230,01/05/2004 00.00.00,3.5,1425.0,275.0,15.2,1155.0,185.0,709.0,110.0,1936.0,1789.0,17.8,66.8,1.3460

### The Task

##### The given task is to perform the linear regression on this dataset 
##### And predict the benzene content which is the column "C6H6(GT)" and all the remaining columns as features
##### The preprocessing techniques should be applied to the dataset like transformation and scaling
##### Transformation should includeboth log transformation and the boxcox transformation
##### Scaling should be of StandardScaler
##### The scores should be using the r2_score and the mean_squared_error
##### Prediction of new set of features should also be performed

Preprocessing the Data

# 1. Applying BoxCox Transformation

In [27]:
import numpy

In [28]:
data_pd = data_pd.drop(columns = "Datetime")

In [29]:
data_pd.head()

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888

In [30]:
skewness = data_pd.skew()

In [31]:
skewness

CO(GT)           1.066209
PT08.S1(CO)      0.565403
NMHC(GT)         1.485345
C6H6(GT)         0.998210
PT08.S2(NMHC)    0.351000
NOx(GT)          0.866116
PT08.S3(NOx)     0.832733
NO2(GT)          0.074280
PT08.S4(NO2)     0.691220
PT08.S5(O3)      0.337771
T                0.626299
RH               0.008160
AH               0.733666
dtype: float64

In [32]:
from scipy.stats import boxcox

In [33]:
values = []
for i,v in enumerate(skewness):
    if -1<v<1:
        continue
    else:
        values.append(skewness.index[i])

In [34]:
values

['CO(GT)', 'NMHC(GT)']

In [35]:
lambdas = {}
logged =[]
for i in values:
    try:
        boxcox_ = boxcox(data_pd[i])
        lambdas[i] = boxcox_[1]
        data_pd[i] = boxcox_[0]
    except Exception as e:
        print(f"The column {i} has negative values!! So performing log1p transform")
        data_pd[i] = np.log1p(data_pd[i])
        logged.append(i)

In [36]:
data_pd.head()

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,1.070226,1360.0,6.456056,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,0.752257,1292.0,5.987233,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,0.865526,1402.0,5.610123,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,0.865526,1376.0,5.463505,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,0.496704,1272.0,4.789025,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888

In [37]:
lambdas

{'CO(GT)': 0.23299381281620474, 'NMHC(GT)': 0.09722772892173977}

In [38]:
data_pd.skew()

CO(GT)          -0.021697
PT08.S1(CO)      0.565403
NMHC(GT)        -0.019571
C6H6(GT)         0.998210
PT08.S2(NMHC)    0.351000
NOx(GT)          0.866116
PT08.S3(NOx)     0.832733
NO2(GT)          0.074280
PT08.S4(NO2)     0.691220
PT08.S5(O3)      0.337771
T                0.626299
RH               0.008160
AH               0.733666
dtype: float64

In [39]:
X_bc_data = data_pd.drop(columns=["C6H6(GT)"],axis=1)

In [40]:
y_bc_data = data_pd["C6H6(GT)"]

In [41]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.model_selection import train_test_split

In [42]:
X_bc_ss = StandardScaler()

In [43]:
xtrain_bc,xtest_bc,ytrain_bc,ytest_bc = train_test_split(X_bc_data,y_bc_data,test_size=0.3)

In [44]:
xtrain_bc_scaled = X_bc_ss.fit_transform(xtrain_bc)
xtest_bc_scaled = X_bc_ss.transform(xtest_bc)

In [45]:
lr_bc = LinearRegression()

In [46]:
lr_bc.fit(xtrain_bc_scaled,ytrain_bc)

LinearRegression()

In [47]:
ypred_bc = lr_bc.predict(xtest_bc_scaled)

In [48]:
r2_score(ytest_bc,ypred_bc)

0.9892663334578188

In [49]:
mean_squared_error(ytest_bc,ypred_bc)

0.6539596817901767

# Lasso Regression

In [51]:
xtrain_bc,xtest_bc,ytrain_bc,ytest_bc = train_test_split(X_bc_data,y_bc_data,test_size=0.3)

In [52]:
xtrain_bc.head()

,CO(GT),PT08.S1(CO),NMHC(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
782,-0.481598,922.0,4.400934,541.0,45.0,1453.0,57.0,1246.0,432.0,13.3,53.6,0.8169
306,1.117585,1209.0,7.421422,1097.0,207.0,837.0,129.0,1746.0,1147.0,13.1,54.8,0.8234
461,0.000000,900.0,4.900098,643.0,55.0,1339.0,74.0,1089.0,455.0,12.4,31.9,0.4583
487,0.000000,973.0,4.760030,631.0,44.0,1287.0,64.0,1240.0,541.0,14.8,40.8,0.6814
344,-0.342257,902.0,4.363890,568.0,38.0,1450.0,54.0,1253.0,479.0,9.1,68.1,0.7890

In [53]:
from sklearn.model_selection import KFold

In [54]:
kf = KFold(n_splits=5,shuffle=True,random_state = 42)

In [55]:
from sklearn.pipeline import Pipeline

In [56]:
from sklearn.preprocessing import StandardScaler, PolynomialFeatures

In [57]:
from sklearn.linear_model import Lasso

In [58]:
lasso_pipeline = Pipeline([
    ('poly',PolynomialFeatures()),
    ('scaler',StandardScaler()),
    ('lasso',Lasso())
])

In [59]:
param_grid_lasso = {
    'poly__degree' : [2,3,5],
    'lasso__alpha' : [0.1,0.001,1,10]
}

In [60]:
from sklearn.model_selection import GridSearchCV

In [61]:
grid_lasso = GridSearchCV(lasso_pipeline, param_grid_lasso,cv=kf,scoring='neg_mean_squared_error')

In [ ]:
grid_lasso.fit(xtrain_bc,ytrain_bc)

In [ ]:
best_lasso = grid_lasso.best_estimator_

In [ ]:
grid_lasso.best_params_

In [ ]:
y_pred_lasso = best_lasso.predict(xtest_bc)

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error

In [ ]:
mse_lasso = mean_squared_error(ytest_bc,y_pred_lasso)

In [ ]:
r2_lasso = r2_score(ytest_bc,y_pred_lasso)

In [ ]:
print(f"MSE Lasso Regression = {mse_lasso}")
print(f"R2_Score Lasso Regression = {r2_lasso}")

## LassoCV

In [ ]:
from sklearn.linear_model import LassoCV

In [ ]:
import numpy as np

In [ ]:
kf_bc = KFold(n_splits=5,shuffle=True)

In [ ]:
Lscv = LassoCV(alphas=np.geomspace(1e-9,1e0,10),cv=kf_bc)

In [ ]:
Lscv.fit(xtrain_bc,ytrain_bc)

In [ ]:
y_pr_bc_lcv = Lscv.predict(xtest_bc)

In [ ]:
r2_LassoCV = r2_score(ytest_bc,y_pr_bc_lcv)

In [ ]:
mse_LassoCV = mean_squared_error(ytest_bc,y_pr_bc_lcv)

In [ ]:
print(f"The MSE value for LassoCV = {mse_LassoCV}")
print(f"The R2 value for LassoCV = {r2_LassoCV}")

# Ridge Regression

In [ ]:
from sklearn.linear_model import Ridge

In [ ]:
ridge_pipeline = Pipeline([
    ('poly',PolynomialFeatures()),
    ('scaler',StandardScaler()),
    ('ridge',Ridge())
])

In [ ]:
param_grid_ridge = {
    'poly__degree' : [2,3,5],
    'ridge__alpha' : [0.1,0.001,1,10]
}

In [ ]:
grid_ridge = GridSearchCV(ridge_pipeline, param_grid_ridge,cv=kf,scoring='neg_mean_squared_error')

In [ ]:
grid_ridge.fit(xtrain_bc,ytrain_bc)

In [ ]:
best_ridge = grid_ridge.best_estimator_

In [ ]:
grid_ridge.best_params_

In [ ]:
y_pred_ridge = best_ridge.predict(xtest_bc)

In [ ]:
mse_ridge = mean_squared_error(ytest_bc,y_pred_ridge)

In [ ]:
r2_ridge = r2_score(ytest_bc,y_pred_ridge)

In [ ]:
print(f"MSE Ridge Regression = {mse_ridge}")
print(f"R2 Ridge Regression = {r2_ridge}")

## RidgeCv

In [ ]:
from sklearn.linear_model import RidgeCV

In [ ]:
Rscv = RidgeCV(alphas=np.geomspace(1e-9,1e0,10),cv=kf_bc)

In [ ]:
Rscv.fit(xtrain_bc,ytrain_bc)

In [ ]:
y_pr_bc_rcv = Rscv.predict(xtest_bc)

In [ ]:
r2_RidgeCV = r2_score(ytest_bc,y_pr_bc_rcv)
mse_RidgeCV = mean_squared_error(ytest_bc,y_pr_bc_rcv)
print(f"The MSE value for RidgeCV = {mse_RidgeCV}")
print(f"The R2 value for RidgeCV = {r2_RidgeCV}")

# Elastic Net Regression

In [ ]:
from sklearn.linear_model import ElasticNet

In [ ]:
bc_pipe = Pipeline([
    ('pf',PolynomialFeatures(include_bias=False)),
    ('ss',StandardScaler()),
    ('en',ElasticNet())
])

In [ ]:
param_g_bc = {
    'pf__degree': [2,3,5],
    'en__alpha' : [0.1,0.001,1,10],
    'en__l1_ratio' : [0.2,0.5,0.8]
}

In [ ]:
grid_bc = GridSearchCV(bc_pipe,param_g_bc,cv=kf,scoring='neg_mean_squared_error')

In [ ]:
grid_bc.fit(xtrain_bc,ytrain_bc)

In [ ]:
best_model_bc = grid_bc.best_estimator_

In [ ]:
grid_bc.best_params_

In [ ]:
grid_bc.best_score_

In [ ]:
best_model_bc.fit(xtrain_bc,ytrain_bc)

In [ ]:
y_pr_bc_en = best_model_bc.predict(xtest_bc)

In [ ]:
r2_en = r2_score(ytest_bc,y_pr_bc_en)

In [ ]:
mse_en = mean_squared_error(ytest_bc,y_pr_bc_en)

In [ ]:
print(f"MSE ElasticNet Regression = {mse_en}")
print(f"R2 ElasticNet Regression = {r2_en}")

## ElasticNetCV

In [ ]:
from sklearn.linear_model import ElasticNetCV

In [ ]:
Encv = ElasticNetCV(alphas=np.geomspace(1e-9,1e0,10),cv=kf_bc)

In [ ]:
Encv.fit(xtrain_bc,ytrain_bc)

In [ ]:
y_pr_bc_ecv = Encv.predict(xtest_bc)

In [ ]:
r2_encv = r2_score(ytest_bc,y_pr_bc_ecv)
mse_encv = mean_squared_error(ytest_bc,y_pr_bc_ecv)
print(f"The MSE value for ElasticNetCV = {mse_encv}")
print(f"The R2 value for ElasticNetCV = {r2_encv}")